import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Utube Transcript Analyzer",
  description: "Generated by create next app",
};
// comment
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${roboto.className}  antialiased`}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <div className='container mx-auto px-4'>{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
